### ISSUE TITLE
Is it possible to log to custom log files ?

### ISSUE THREAD

**Issue by Altroo** [atkinchris/next-logger#20]
Hello, 

As the title say i would like for example to log two files, debug.log for debug logs & error.log to catch errors, i couldn't find something related to this in the library, but perhaps i'm missing something, or override some config ?

Thank's in advance.

**Comment by Altroo** [comment]
Found it : 

```
// next-logger.config.js
const pino = require('pino');
const logger = (defaultConfig) =>
	pino({
		...defaultConfig,
		formatters: {
			level: (label) => {
				return { level: label };
			},
		},
		timestamp: pino.stdTimeFunctions.isoTime,
	}, pino.destination(`${__dirname}/logs/debug.log`));
module.exports = {
	logger,
};
```

**Comment by cklat** [comment]
I'm having the same goal but couldn't get it to work with your solution (yet).

Is there anything I need to change elsewhere when defining a custom logger which, I assume, above mentioned gist represents? 

Thanks for the help!

**Comment by Altroo** [comment]
> I'm having the same goal but couldn't get it to work with your solution (yet).
> 
> Is there anything I need to change elsewhere when defining a custom logger which, I assume, above mentioned gist represents?
> 
> Thanks for the help!

I've checked and i've used the same code as above with "pino": "^8.15.1".
I've created the folder logs on the root directory & inside it an empty debug.log file

**Comment by Altroo** [comment]
@cklat sorry bro, i dunno how to help with that, if it works with js then just leave it in js it's not a big deal.
